server:
  port: 9180
spring:
  application:
    name: auth-service
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:        web-allow-others: true
  datasource:
    url: jdbc:h2:~/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create

jwt:
  secret: $2a$10$HlzMvb9OQayvlWfX5pzJTeZvH30eKwnc6gE0C3idjDvbQt4XJMTki
  expiration: 10000