server:
   port: 9080
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
spring:
  application:
    name: gateway-service
zuul:
  ignored-services:
   - path=*
  routes: 
    loan-service:
      path: /api/loanapplications/
    customer-service:
      path: /api/customers/
    service-id: 
      LOAN-SERVICE
      CUSTOMER-SERVICE
          
jwt:
  header: Authorization
  secret: $2a$10$HlzMvb9OQayvlWfX5pzJTeZvH30eKwnc6gE0C3idjDvbQt4XJMTki
       